apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xn8t7iokg-go 
  janus-idp.io/tekton: xn8t7iokg-go
  backstage.io/kubernetes-id: xn8t7iokg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xn8t7iokg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml