apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xn8t7iokg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xn8t7iokg-go 
  name: xn8t7iokg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xn8t7iokg-go 
